services:
  postgres:
    mem_limit: 512m
    mem_reservation: 512m
    container_name: ecore_postgres
    image: postgres:14
    environment:
      - POSTGRES_DB=zero_db
      - POSTGRES_USER=zero
      - POSTGRES_PASSWORD=secret
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - local

  rabbitmq:
    mem_limit: 256m
    mem_reservation: 256m
    container_name: ecore_rabbitmq
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=zero
      - RABBITMQ_DEFAULT_PASS=secret
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    networks:
      - local

  springboot:
    container_name: ecore_springboot
    platform: linux/amd64
    build: ./
    image: ecore/springboot:latest
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    networks:
      - local

volumes:
  pgsql_data:
    driver: local
  rabbitmq:
    driver: local

networks:
  local:
    driver: bridge