services:
  postgres:
    mem_limit: 512m
    mem_reservation: 512m
    container_name: ecore_postgres
    image: postgres:14
    environment:
      - POSTGRES_DB=zero_db
      - POSTGRES_USER=zero
      - POSTGRES_PASSWORD=secret
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - local

  mongo:
    image: mongo
    mem_limit: 512m
    mem_reservation: 512m
    restart: always
    container_name: ecore_mongo
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
    depends_on:
      - mongo2
      - mongo3
    links:
      - mongo2
      - mongo3
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: employee
    volumes:
      - ./config/mongo/rs-init.sh:/scripts/rs-init.sh
      - ./config/mongo/init.js:/scripts/init.js
    networks:
      - local

  mongo2:
    image: mongo
    mem_limit: 512m
    mem_reservation: 512m
    container_name: ecore_mongo2
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
    ports:
      - 27018:27017
    networks:
      - local

  mongo3:
    image: mongo
    mem_limit: 512m
    mem_reservation: 512m
    container_name: ecore_mongo3
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
    ports:
      - 27019:27017
    networks:
      - local

  rabbitmq:
    mem_limit: 256m
    mem_reservation: 256m
    container_name: ecore_rabbitmq
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=zero
      - RABBITMQ_DEFAULT_PASS=secret
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    networks:
      - local

  prometheus:
    container_name: ecore_prometheus
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    networks:
      - local

  grafana:
    container_name: ecore_grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - local

  springboot:
    container_name: ecore_springboot
    platform: linux/amd64
    build: ./
    image: ecore/springboot:latest
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    networks:
      - local

volumes:
  pgsql_data:
    driver: local
  rabbitmq:
    driver: local
  prometheus_data:
  grafana_data:

networks:
  local:
    driver: bridge