services:
  postgres:
    container_name: ecore_postgres
    image: postgres:14
    environment:
      - POSTGRES_DB=zero_db
      - POSTGRES_USER=zero
      - POSTGRES_PASSWORD=secret
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - local
  springboot:
    container_name: ecore_springboot
    platform: linux/amd64
    build: ./
    image: ecore/springboot:latest
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    networks:
      - local

volumes:
  pgsql_data:
    driver: local

networks:
  local:
    driver: bridge