global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: "/api/actuator/prometheus"
    static_configs:
      - targets: ['springboot:8080']
        labels:
          application: 'api-ecore'